FROM m0elnx/ubuntu-32bit
MAINTAINER Wenbo Wang <wenbo.wang@belkin.com>

RUN sed -i 's|http://archive.ubuntu.com|http://mirrors.yun-idc.com|' /etc/apt/sources.list
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install build-essential \
	    libncurses5-dev \
	    libtool \
	    m4 \
	    automake \
	    autoconf \
	    libglib2.0-dev \
	    device-tree-compiler \
	    bison \
	    flex \
	    libreadline6-dev \
	    texinfo \
	    gawk \
	    lua5.1 \
	    tidy \
	    nodejs-legacy \
	    sharutils \
	    genext2fs \
	    mtd-utils \
	    gettext \
	    scons \
	    cmake \
	    rsync \
	    bc \
	    tclsh \
	    zip \
	    fakeroot \
	    dos2unix \
	    git \
	    sudo \
	    libelf1 \
	    help2man \
	    autopoint \
	    android-tools-fsutils \
		chrpath \
		diffstat

ADD http://commondatastorage.googleapis.com/git-repo-downloads/repo /usr/local/bin/repo
RUN chmod 755 /usr/local/bin/repo
ADD uname /usr/local/bin
ADD dexec /usr/local/bin
ADD p4 /usr/local/bin
ADD sudoers /etc
ENTRYPOINT ["/usr/local/bin/dexec"]
